export default actionType = {
    LOGIN_REQUEST :'LOGIN_REQUEST',

    LOGIN_SUCCEED :'LOGIN_SUCCEED',

    SIGNUP_REQUEST :'SIGNUP_REQUEST',

    SIGNUP_SUCCEED :'SIGNUP_SUCCEED',

    IS_ERROR :'IS_ERROR',

    LOAD_QUESTION_REQUEST: 'LOAD_QUESTION_REQUEST',

    LOAD_QUESTION_SUCCEED: 'LOAD_QUESTION_SUCCEED',

    STORE_QUESTION: 'STORE_QUESTION',
    
    RESULT: 'RESULT',
}